package com.tasks.Tasks.exception;

public class UserFoundException extends RuntimeException{
    public UserFoundException(String message){
        super(message);
    }
}
